server:
  port: 9093

spring:
  amqp:
    deserialization:
      trust:
        all: true
  rabbitmq:
    host: localhost
    port: 5672
    username: BilgeAdmin
    password: Aa123456
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/HasAppointmentDB
  jpa:
    hibernate:
      ddl-auto: create

my-application-appointment:
  doctor-end-point: http://localhost:9091/doctor
  secret-key: "bAjAfl&ato9ruwrichlyUc1Lfaprafr8soNoCr!BramaTR7mojicr1wRI0*oC3is"
  secret-key-2: ${SECRETKEY}
